import PDFDocument from 'pdfkit';

const paperSizeHeight = 841.89;
const paperSizeWidth = 595.28;
const paperMargin = 30;

export async function createUserResume(userData) {
  const doc = new PDFDocument({
    size: [paperSizeWidth, paperSizeHeight],
    margin: paperMargin,
  });

  generateHeader(doc, userData);
  generatePersonalDetails(doc, userData.userDetail[0]);
  generateEducationDetails(doc, userData.userEducation);
  generateJobExperience(doc, userData.userJobExperience);
  generateSkills(doc, userData.userSkill);
  generatePreferences(doc, userData);

  generateFooter(doc);

  return doc;
}

function generateHeader(doc, userData) {
  doc
    .fontSize(20)
    .text(userData.userDetail[0].name, { align: 'center' })
    .fontSize(12)
    .text(`email: ${userData.userDetail[0].email}`, { align: 'center' })
    .text(`mobile: ${userData.phoneNumber || 'N/A'}`, { align: 'center' })
    .moveDown();
}

function generatePersonalDetails(doc, userDetail) {
  doc.fontSize(16).text('Personal Details', { underline: true }).moveDown(0.5);

  doc
    .fontSize(12)
    .text(`Work Status: ${userDetail.workStatus}`)
    .text(`City: ${userDetail.city || 'N/A'}`)
    .text(`Current Location: ${userDetail.currLocation}`)
    .text(`Hometown: ${userDetail.hometown}`)
    .text(`Gender: ${userDetail.gender}`)
    .text(`DOB: ${userDetail.dob}`)
    .text(
      `Total Experience: ${userDetail.totalExpYear} Years ${userDetail.totalExpMonth} Months`,
    )
    .text(`Current Salary: ${userDetail.currSalary}`)
    .moveDown();
}

function generateEducationDetails(doc, userEducation) {
  doc.fontSize(16).text('Education Details', { underline: true }).moveDown(0.5);

  userEducation.forEach((edu) => {
    doc
      .fontSize(12)
      .text(`Degree: ${edu.degree} in ${edu.specialization}`)
      .text(`College: ${edu.collegeName}`)
      .text(`Completion: ${edu.completionMonth} ${edu.completionYear}`)
      .text(`School Medium: ${edu.schoolMedium}`)
      .moveDown();
  });
}

function generateJobExperience(doc, userJobExperience) {
  doc.fontSize(16).text('Job Experience', { underline: true }).moveDown(0.5);

  userJobExperience.forEach((job) => {
    doc
      .fontSize(12)
      .text(`Job Title: ${job.jobTitle}`)
      .text(`Company: ${job.companyName}`)
      .text(`Industry: ${job.industry}`)
      .text(
        `Duration: ${job.startMonth} ${job.startYear} - ${job.currentlyWorkingHere === 'Yes' ? 'Present' : 'Ended'}`,
      )
      .moveDown();
  });
}

function generateSkills(doc, userSkills) {
  doc.fontSize(16).text('Skills', { underline: true }).moveDown(0.5);

  userSkills.forEach((skill) => {
    doc.fontSize(12).text(`• ${skill.skillName}`);
  });
  doc.moveDown();
}

function generatePreferences(doc, userData) {
  const {
    // prefferdJobRegion,
    userPreffLang,
    userPreffShift,
    userPreffWorkplace,
    userPreffEmploymentType,
  } = userData;

  doc.fontSize(16).text('Preferences', { underline: true }).moveDown(0.5);

  // if (prefferdJobRegion?.length > 0) {
  //   doc.fontSize(12).text('Preferred Job Regions:');
  //   prefferdJobRegion.forEach((region) => {
  //     doc.text(`• ${region.name}`);
  //   });
  //   doc.moveDown();
  // }

  if (userPreffLang?.length > 0) {
    doc.fontSize(12).text('Preferred Languages:');
    userPreffLang.forEach((lang) => {
      doc.text(`• ${lang.language}`);
    });
    doc.moveDown();
  }

  doc
    .fontSize(12)
    .text(`Preferred Shift: ${userPreffShift[0]?.shift || 'N/A'}`)
    .text(`Workplace Preference: ${userPreffWorkplace[0]?.workPlace || 'N/A'}`)
    .text(
      `Employment Type: ${userPreffEmploymentType[0]?.employmentType || 'N/A'}`,
    )
    .moveDown();
}

function generateFooter(doc) {
  const footerText = 'Generated by HIRE INDIA WEBSITE. All rights reserved.';
  const footerHeight = 20;
  const footerY = doc.page.height - doc.page.margins.bottom - footerHeight;

  doc.fontSize(10).text(footerText, doc.page.margins.left, footerY, {
    width: doc.page.width - doc.page.margins.left - doc.page.margins.right,
    align: 'center',
  });
}
