import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1763124803538 implements MigrationInterface {
    name = 'Migration1763124803538'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`unit\` ADD \`akashGhoshPath\` varchar(200) NULL`);
        await queryRunner.query(`ALTER TABLE \`walk_through\` CHANGE \`title\` \`title\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`walk_through\` CHANGE \`subtitle\` \`subtitle\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`walk_through\` CHANGE \`image\` \`image\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`walk_through\` CHANGE \`imagePath\` \`imagePath\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`contact_us\` DROP FOREIGN KEY \`FK_21a409f03c342bf8bb747c90161\``);
        await queryRunner.query(`ALTER TABLE \`contact_us\` CHANGE \`accountId\` \`accountId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`contact_us\` CHANGE \`firstName\` \`firstName\` varchar(55) NULL`);
        await queryRunner.query(`ALTER TABLE \`contact_us\` CHANGE \`LastName\` \`LastName\` varchar(55) NULL`);
        await queryRunner.query(`ALTER TABLE \`contact_us\` CHANGE \`email\` \`email\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`contact_us\` CHANGE \`phoneNumber\` \`phoneNumber\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`contact_us\` CHANGE \`code\` \`code\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`contact_us\` CHANGE \`message\` \`message\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`login_history\` CHANGE \`loginTime\` \`loginTime\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`login_history\` CHANGE \`logoutTime\` \`logoutTime\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`login_history\` CHANGE \`ip\` \`ip\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`notification\` CHANGE \`title\` \`title\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`notification\` CHANGE \`desc\` \`desc\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`notification\` CHANGE \`type\` \`type\` enum ('NEW PRODUCT', 'NEW ACCOUNT', 'CONTACT US', 'QNA', 'FEEDBACK', 'INVOICE', 'STAFF', 'TICKET', 'USER PRODUCT', 'USER ACCOUNT', 'USER INVOICE', 'USER PAYMENT', 'USER TICKET', 'OFFER', 'LOGIN', 'DEMO') NULL`);
        await queryRunner.query(`ALTER TABLE \`notification\` CHANGE \`accountId\` \`accountId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`rating_feedback\` CHANGE \`desc\` \`desc\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`rating_feedback\` CHANGE \`accountId\` \`accountId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`subject\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`subject\` CHANGE \`image\` \`image\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`subject\` CHANGE \`imagePath\` \`imagePath\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`class\` CHANGE \`image\` \`image\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`class\` CHANGE \`imagePath\` \`imagePath\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`user_progress\` CHANGE \`courseId\` \`courseId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_progress\` CHANGE \`unitId\` \`unitId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_progress\` CHANGE \`studyMaterialId\` \`studyMaterialId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_progress\` CHANGE \`contentId\` \`contentId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`study_material\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`study_material\` CHANGE \`fileUrl\` \`fileUrl\` varchar(500) NULL`);
        await queryRunner.query(`ALTER TABLE \`study_material\` CHANGE \`filePath\` \`filePath\` varchar(500) NULL`);
        await queryRunner.query(`ALTER TABLE \`study_material\` CHANGE \`unitId\` \`unitId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`video_lecture\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`video_lecture\` CHANGE \`videoUrl\` \`videoUrl\` varchar(500) NULL`);
        await queryRunner.query(`ALTER TABLE \`video_lecture\` CHANGE \`videoPath\` \`videoPath\` varchar(500) NULL`);
        await queryRunner.query(`ALTER TABLE \`video_lecture\` CHANGE \`thumbnailUrl\` \`thumbnailUrl\` varchar(500) NULL`);
        await queryRunner.query(`ALTER TABLE \`video_lecture\` CHANGE \`thumbnailPath\` \`thumbnailPath\` varchar(500) NULL`);
        await queryRunner.query(`ALTER TABLE \`unit\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`unit\` CHANGE \`imgUrl\` \`imgUrl\` varchar(200) NULL`);
        await queryRunner.query(`ALTER TABLE \`unit\` CHANGE \`imgPath\` \`imgPath\` varchar(200) NULL`);
        await queryRunner.query(`ALTER TABLE \`unit\` CHANGE \`courseId\` \`courseId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`courses\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`courses\` CHANGE \`imageUrl\` \`imageUrl\` varchar(500) NULL`);
        await queryRunner.query(`ALTER TABLE \`courses\` CHANGE \`imagepath\` \`imagepath\` varchar(500) NULL`);
        await queryRunner.query(`ALTER TABLE \`courses\` CHANGE \`thumbnailpath\` \`thumbnailpath\` varchar(500) NULL`);
        await queryRunner.query(`ALTER TABLE \`courses\` CHANGE \`thumbnailUrl\` \`thumbnailUrl\` varchar(500) NULL`);
        await queryRunner.query(`ALTER TABLE \`courses\` CHANGE \`totalDuration\` \`totalDuration\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`courses\` CHANGE \`authorMessage\` \`authorMessage\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`courses\` CHANGE \`startDate\` \`startDate\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`courses\` CHANGE \`endDate\` \`endDate\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`courses\` CHANGE \`subjectId\` \`subjectId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`courses\` CHANGE \`languageId\` \`languageId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`courses\` CHANGE \`deletionReason\` \`deletionReason\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`courses\` CHANGE \`classId\` \`classId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`language\` CHANGE \`name\` \`name\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`topic\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`user_detail\` CHANGE \`name\` \`name\` varchar(55) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_detail\` CHANGE \`gender\` \`gender\` enum ('MALE', 'FEMALE', 'OTHERS') NULL`);
        await queryRunner.query(`ALTER TABLE \`user_detail\` CHANGE \`englishLevel\` \`englishLevel\` enum ('Beginner', 'Intermediate', 'Exparts', 'Pro_Master') NULL`);
        await queryRunner.query(`ALTER TABLE \`user_detail\` CHANGE \`dob\` \`dob\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`user_detail\` CHANGE \`address\` \`address\` varchar(5000) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_detail\` CHANGE \`profile\` \`profile\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`user_detail\` CHANGE \`profileName\` \`profileName\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`user_detail\` CHANGE \`accountId\` \`accountId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_detail\` CHANGE \`topicId\` \`topicId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_detail\` CHANGE \`goalId\` \`goalId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_detail\` CHANGE \`countryId\` \`countryId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_detail\` CHANGE \`languageId\` \`languageId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_detail\` CHANGE \`budgetId\` \`budgetId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_detail\` CHANGE \`qualificationId\` \`qualificationId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`country\` CHANGE \`code\` \`code\` varchar(10) NULL`);
        await queryRunner.query(`ALTER TABLE \`state\` CHANGE \`code\` \`code\` varchar(10) NULL`);
        await queryRunner.query(`ALTER TABLE \`state\` CHANGE \`countryId\` \`countryId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`city\` CHANGE \`stateId\` \`stateId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`tutor_detail\` CHANGE \`name\` \`name\` varchar(55) NULL`);
        await queryRunner.query(`ALTER TABLE \`tutor_detail\` CHANGE \`tutorId\` \`tutorId\` varchar(20) NULL`);
        await queryRunner.query(`ALTER TABLE \`tutor_detail\` CHANGE \`gender\` \`gender\` enum ('MALE', 'FEMALE', 'OTHERS') NULL`);
        await queryRunner.query(`ALTER TABLE \`tutor_detail\` CHANGE \`dob\` \`dob\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`tutor_detail\` CHANGE \`profileImage\` \`profileImage\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tutor_detail\` CHANGE \`profileImagePath\` \`profileImagePath\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tutor_detail\` CHANGE \`document\` \`document\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tutor_detail\` CHANGE \`documentName\` \`documentName\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tutor_detail\` CHANGE \`bio\` \`bio\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`tutor_detail\` CHANGE \`accountId\` \`accountId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`tutor_detail\` CHANGE \`cityId\` \`cityId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`tutor_detail\` CHANGE \`subjectId\` \`subjectId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`tutor_detail\` CHANGE \`countryId\` \`countryId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`tutor_detail\` CHANGE \`languageId\` \`languageId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`tutor_detail\` CHANGE \`qualificationId\` \`qualificationId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`rating\` CHANGE \`comment\` \`comment\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`rating\` CHANGE \`tutorId\` \`tutorId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`rating\` CHANGE \`courseId\` \`courseId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`staff_detail\` CHANGE \`name\` \`name\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`staff_detail\` CHANGE \`email\` \`email\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`staff_detail\` CHANGE \`dob\` \`dob\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`staff_detail\` CHANGE \`gender\` \`gender\` enum ('MALE', 'FEMALE', 'OTHERS') NULL`);
        await queryRunner.query(`ALTER TABLE \`staff_detail\` CHANGE \`city\` \`city\` varchar(20) NULL`);
        await queryRunner.query(`ALTER TABLE \`staff_detail\` CHANGE \`state\` \`state\` varchar(20) NULL`);
        await queryRunner.query(`ALTER TABLE \`staff_detail\` CHANGE \`country\` \`country\` varchar(20) NULL`);
        await queryRunner.query(`ALTER TABLE \`staff_detail\` CHANGE \`pin\` \`pin\` varchar(10) NULL`);
        await queryRunner.query(`ALTER TABLE \`staff_detail\` CHANGE \`accountId\` \`accountId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`staff_detail\` CHANGE \`updatedBy\` \`updatedBy\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_permission\` CHANGE \`accountId\` \`accountId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_permission\` CHANGE \`menuId\` \`menuId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user_permission\` CHANGE \`permissionId\` \`permissionId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`account\` CHANGE \`phoneNumber\` \`phoneNumber\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`account\` CHANGE \`email\` \`email\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`account\` CHANGE \`password\` \`password\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`account\` CHANGE \`lockedUntil\` \`lockedUntil\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`user_purchase\` CHANGE \`courseId\` \`courseId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_purchase\` CHANGE \`videoLectureId\` \`videoLectureId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_purchase\` CHANGE \`studyMaterialId\` \`studyMaterialId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_purchase\` CHANGE \`unitId\` \`unitId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_purchase\` CHANGE \`sessionId\` \`sessionId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_purchase\` CHANGE \`merchantOrderId\` \`merchantOrderId\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_purchase\` CHANGE \`originalAmount\` \`originalAmount\` decimal(10,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_purchase\` CHANGE \`couponCode\` \`couponCode\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_purchase\` CHANGE \`transactionId\` \`transactionId\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_purchase\` CHANGE \`paymentIntentId\` \`paymentIntentId\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_purchase\` CHANGE \`expiresAt\` \`expiresAt\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`tutor_block\` CHANGE \`reason\` \`reason\` varchar(200) NULL`);
        await queryRunner.query(`ALTER TABLE \`setting\` CHANGE \`title\` \`title\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`setting\` CHANGE \`user_domain\` \`user_domain\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`setting\` CHANGE \`admin_domain\` \`admin_domain\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`setting\` CHANGE \`mobile_domain\` \`mobile_domain\` varchar(150) NULL`);
        await queryRunner.query(`ALTER TABLE \`setting\` CHANGE \`logo\` \`logo\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`setting\` CHANGE \`logoPath\` \`logoPath\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`setting\` CHANGE \`facebook\` \`facebook\` varchar(500) NULL`);
        await queryRunner.query(`ALTER TABLE \`setting\` CHANGE \`linkedIn\` \`linkedIn\` varchar(500) NULL`);
        await queryRunner.query(`ALTER TABLE \`setting\` CHANGE \`twitter\` \`twitter\` varchar(500) NULL`);
        await queryRunner.query(`ALTER TABLE \`setting\` CHANGE \`instagram\` \`instagram\` varchar(500) NULL`);
        await queryRunner.query(`ALTER TABLE \`setting\` CHANGE \`whatsApp\` \`whatsApp\` varchar(500) NULL`);
        await queryRunner.query(`ALTER TABLE \`search_history\` CHANGE \`keyword\` \`keyword\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`search_history\` CHANGE \`accountId\` \`accountId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`session\` CHANGE \`amount\` \`amount\` decimal(10,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`session\` CHANGE \`purchaseId\` \`purchaseId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`session\` CHANGE \`notes\` \`notes\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`page\` CHANGE \`imageUrl\` \`imageUrl\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`page\` CHANGE \`imagePath\` \`imagePath\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`news\` CHANGE \`heading\` \`heading\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`news\` CHANGE \`desc\` \`desc\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`news\` CHANGE \`image\` \`image\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`news\` CHANGE \`imagePath\` \`imagePath\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`notice\` CHANGE \`image\` \`image\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`notice\` CHANGE \`imagePath\` \`imagePath\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`faq\` CHANGE \`question\` \`question\` varchar(150) NULL`);
        await queryRunner.query(`ALTER TABLE \`faq\` CHANGE \`answer\` \`answer\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`fixed_session\` CHANGE \`purchaseId\` \`purchaseId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`fixed_session\` CHANGE \`notes\` \`notes\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`category\` CHANGE \`image\` \`image\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`category\` CHANGE \`imagePath\` \`imagePath\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`book\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`book\` CHANGE \`coverImage\` \`coverImage\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`book\` CHANGE \`coverImagePath\` \`coverImagePath\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`book_image\` CHANGE \`bookId\` \`bookId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`banner\` CHANGE \`image\` \`image\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`banner\` CHANGE \`imagePath\` \`imagePath\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`contact_us\` ADD CONSTRAINT \`FK_21a409f03c342bf8bb747c90161\` FOREIGN KEY (\`accountId\`) REFERENCES \`account\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`notification\` ADD CONSTRAINT \`FK_00abcf7b2089a5c05f0aedc5676\` FOREIGN KEY (\`accountId\`) REFERENCES \`account\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`rating_feedback\` ADD CONSTRAINT \`FK_3a4b6f59bafa155b2d185c6b1c6\` FOREIGN KEY (\`accountId\`) REFERENCES \`account\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`user_progress\` ADD CONSTRAINT \`FK_b5d0e1b57bc6c761fb49e79bf89\` FOREIGN KEY (\`userId\`) REFERENCES \`account\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_progress\` ADD CONSTRAINT \`FK_18a9800c645b27305a3d55961e8\` FOREIGN KEY (\`courseId\`) REFERENCES \`courses\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_progress\` ADD CONSTRAINT \`FK_4e8ebae6a86a6d1483a0805f48c\` FOREIGN KEY (\`unitId\`) REFERENCES \`unit\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_progress\` ADD CONSTRAINT \`FK_d6e1520d30ecc804051502cec69\` FOREIGN KEY (\`studyMaterialId\`) REFERENCES \`study_material\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`study_material\` ADD CONSTRAINT \`FK_bb8358d7c0bc176266b00a3d345\` FOREIGN KEY (\`videoLectureId\`) REFERENCES \`video_lecture\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`study_material\` ADD CONSTRAINT \`FK_f7eb69acae2d90013542e3e584a\` FOREIGN KEY (\`unitId\`) REFERENCES \`unit\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`video_lecture\` ADD CONSTRAINT \`FK_dfb3a19f9b575657e245f46d7a1\` FOREIGN KEY (\`unitId\`) REFERENCES \`unit\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`unit\` ADD CONSTRAINT \`FK_c88f881f8a9aa8be02740289776\` FOREIGN KEY (\`courseId\`) REFERENCES \`courses\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`courses\` ADD CONSTRAINT \`FK_4fc71ca03df7fa563050d553c39\` FOREIGN KEY (\`subjectId\`) REFERENCES \`subject\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`courses\` ADD CONSTRAINT \`FK_a09de3e6027500ac44609a8055f\` FOREIGN KEY (\`languageId\`) REFERENCES \`language\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`courses\` ADD CONSTRAINT \`FK_fd1cecfbb001ebcd3a2221dff8c\` FOREIGN KEY (\`classId\`) REFERENCES \`class\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`courses\` ADD CONSTRAINT \`FK_a401fb96f1afa0fcebacd3e8e78\` FOREIGN KEY (\`tutorId\`) REFERENCES \`account\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_detail\` ADD CONSTRAINT \`FK_540d2de9f397b81fd7ee070d631\` FOREIGN KEY (\`accountId\`) REFERENCES \`account\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`user_detail\` ADD CONSTRAINT \`FK_f56bc266a9a1ef8912cbddb5754\` FOREIGN KEY (\`topicId\`) REFERENCES \`topic\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`user_detail\` ADD CONSTRAINT \`FK_91b939d5697198c2b12ba36cddc\` FOREIGN KEY (\`goalId\`) REFERENCES \`goal\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`user_detail\` ADD CONSTRAINT \`FK_0cb17ec996d935f159c77ee536f\` FOREIGN KEY (\`countryId\`) REFERENCES \`country\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`user_detail\` ADD CONSTRAINT \`FK_34b12bec10c7d1e5f5a6189f2a0\` FOREIGN KEY (\`languageId\`) REFERENCES \`language\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`user_detail\` ADD CONSTRAINT \`FK_438c6137a1949713359a59e39de\` FOREIGN KEY (\`budgetId\`) REFERENCES \`budget\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`user_detail\` ADD CONSTRAINT \`FK_0bc43232b53a303a2a6eb40410f\` FOREIGN KEY (\`qualificationId\`) REFERENCES \`qualification\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`state\` ADD CONSTRAINT \`FK_e81c86ceadca8731f5fca8e06f5\` FOREIGN KEY (\`countryId\`) REFERENCES \`country\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`city\` ADD CONSTRAINT \`FK_e99de556ee56afe72154f3ed04a\` FOREIGN KEY (\`stateId\`) REFERENCES \`state\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`tutor_availability\` ADD CONSTRAINT \`FK_dbb3f92f1ca19df010e9ea33397\` FOREIGN KEY (\`tutorId\`) REFERENCES \`tutor_detail\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tutor_detail\` ADD CONSTRAINT \`FK_345fc8b7836d46e07752da898c2\` FOREIGN KEY (\`accountId\`) REFERENCES \`account\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`tutor_detail\` ADD CONSTRAINT \`FK_be4bd22a3df2c55bdb8b12dcb4a\` FOREIGN KEY (\`subjectId\`) REFERENCES \`subject\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`tutor_detail\` ADD CONSTRAINT \`FK_ba84d5cd29a18f53c3ba0a70ca9\` FOREIGN KEY (\`cityId\`) REFERENCES \`city\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`tutor_detail\` ADD CONSTRAINT \`FK_9ed795b33fedfe5c40944fbdb96\` FOREIGN KEY (\`countryId\`) REFERENCES \`country\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`tutor_detail\` ADD CONSTRAINT \`FK_51f74abe9c533c23dfe4a888863\` FOREIGN KEY (\`languageId\`) REFERENCES \`language\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`tutor_detail\` ADD CONSTRAINT \`FK_962e487e0bdb79c8a7fe7d1554a\` FOREIGN KEY (\`qualificationId\`) REFERENCES \`qualification\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`rating\` ADD CONSTRAINT \`FK_0d45dca7852dff42e62c8213e3c\` FOREIGN KEY (\`tutorId\`) REFERENCES \`tutor_detail\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rating\` ADD CONSTRAINT \`FK_1283cbb80fa7bddb804f81fa10d\` FOREIGN KEY (\`courseId\`) REFERENCES \`courses\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`staff_detail\` ADD CONSTRAINT \`FK_73bc1e4f2f974b951fffbf28cce\` FOREIGN KEY (\`accountId\`) REFERENCES \`account\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`user_permission\` ADD CONSTRAINT \`FK_344be4cbbe3c14a1b4fa111e152\` FOREIGN KEY (\`accountId\`) REFERENCES \`account\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`user_permission\` ADD CONSTRAINT \`FK_ecd93ebf7df98c1d09613171e97\` FOREIGN KEY (\`menuId\`) REFERENCES \`menu\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`user_permission\` ADD CONSTRAINT \`FK_a592f2df24c9d464afd71401ff6\` FOREIGN KEY (\`permissionId\`) REFERENCES \`permission\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`user_purchase\` ADD CONSTRAINT \`FK_e52b156f9bccf49aff91f2457d9\` FOREIGN KEY (\`accountId\`) REFERENCES \`account\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_purchase\` ADD CONSTRAINT \`FK_513273a7aa888305c1b895b7030\` FOREIGN KEY (\`courseId\`) REFERENCES \`courses\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_purchase\` ADD CONSTRAINT \`FK_d6435774b614e29f5a62f979ff6\` FOREIGN KEY (\`studyMaterialId\`) REFERENCES \`study_material\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_purchase\` ADD CONSTRAINT \`FK_e8f8e2c19d0489acb953b5a4b89\` FOREIGN KEY (\`unitId\`) REFERENCES \`unit\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tutor_block\` ADD CONSTRAINT \`FK_0a967dadf46742c42bb094617a6\` FOREIGN KEY (\`tutorId\`) REFERENCES \`tutor_detail\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`session\` ADD CONSTRAINT \`FK_3d2f174ef04fb312fdebd0ddc53\` FOREIGN KEY (\`userId\`) REFERENCES \`account\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`session\` ADD CONSTRAINT \`FK_0114764a642df8a4e96d82b88c6\` FOREIGN KEY (\`tutorId\`) REFERENCES \`tutor_detail\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fixed_session\` ADD CONSTRAINT \`FK_ea37f330494fd9d3a16243ec0d0\` FOREIGN KEY (\`userId\`) REFERENCES \`account\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fixed_session\` ADD CONSTRAINT \`FK_09c925f63ca386cf9205d2b5615\` FOREIGN KEY (\`tutorId\`) REFERENCES \`tutor_detail\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`book_image\` ADD CONSTRAINT \`FK_764debb683bba6986f25d7369bf\` FOREIGN KEY (\`bookId\`) REFERENCES \`book\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`book_image\` DROP FOREIGN KEY \`FK_764debb683bba6986f25d7369bf\``);
        await queryRunner.query(`ALTER TABLE \`fixed_session\` DROP FOREIGN KEY \`FK_09c925f63ca386cf9205d2b5615\``);
        await queryRunner.query(`ALTER TABLE \`fixed_session\` DROP FOREIGN KEY \`FK_ea37f330494fd9d3a16243ec0d0\``);
        await queryRunner.query(`ALTER TABLE \`session\` DROP FOREIGN KEY \`FK_0114764a642df8a4e96d82b88c6\``);
        await queryRunner.query(`ALTER TABLE \`session\` DROP FOREIGN KEY \`FK_3d2f174ef04fb312fdebd0ddc53\``);
        await queryRunner.query(`ALTER TABLE \`tutor_block\` DROP FOREIGN KEY \`FK_0a967dadf46742c42bb094617a6\``);
        await queryRunner.query(`ALTER TABLE \`user_purchase\` DROP FOREIGN KEY \`FK_e8f8e2c19d0489acb953b5a4b89\``);
        await queryRunner.query(`ALTER TABLE \`user_purchase\` DROP FOREIGN KEY \`FK_d6435774b614e29f5a62f979ff6\``);
        await queryRunner.query(`ALTER TABLE \`user_purchase\` DROP FOREIGN KEY \`FK_513273a7aa888305c1b895b7030\``);
        await queryRunner.query(`ALTER TABLE \`user_purchase\` DROP FOREIGN KEY \`FK_e52b156f9bccf49aff91f2457d9\``);
        await queryRunner.query(`ALTER TABLE \`user_permission\` DROP FOREIGN KEY \`FK_a592f2df24c9d464afd71401ff6\``);
        await queryRunner.query(`ALTER TABLE \`user_permission\` DROP FOREIGN KEY \`FK_ecd93ebf7df98c1d09613171e97\``);
        await queryRunner.query(`ALTER TABLE \`user_permission\` DROP FOREIGN KEY \`FK_344be4cbbe3c14a1b4fa111e152\``);
        await queryRunner.query(`ALTER TABLE \`staff_detail\` DROP FOREIGN KEY \`FK_73bc1e4f2f974b951fffbf28cce\``);
        await queryRunner.query(`ALTER TABLE \`rating\` DROP FOREIGN KEY \`FK_1283cbb80fa7bddb804f81fa10d\``);
        await queryRunner.query(`ALTER TABLE \`rating\` DROP FOREIGN KEY \`FK_0d45dca7852dff42e62c8213e3c\``);
        await queryRunner.query(`ALTER TABLE \`tutor_detail\` DROP FOREIGN KEY \`FK_962e487e0bdb79c8a7fe7d1554a\``);
        await queryRunner.query(`ALTER TABLE \`tutor_detail\` DROP FOREIGN KEY \`FK_51f74abe9c533c23dfe4a888863\``);
        await queryRunner.query(`ALTER TABLE \`tutor_detail\` DROP FOREIGN KEY \`FK_9ed795b33fedfe5c40944fbdb96\``);
        await queryRunner.query(`ALTER TABLE \`tutor_detail\` DROP FOREIGN KEY \`FK_ba84d5cd29a18f53c3ba0a70ca9\``);
        await queryRunner.query(`ALTER TABLE \`tutor_detail\` DROP FOREIGN KEY \`FK_be4bd22a3df2c55bdb8b12dcb4a\``);
        await queryRunner.query(`ALTER TABLE \`tutor_detail\` DROP FOREIGN KEY \`FK_345fc8b7836d46e07752da898c2\``);
        await queryRunner.query(`ALTER TABLE \`tutor_availability\` DROP FOREIGN KEY \`FK_dbb3f92f1ca19df010e9ea33397\``);
        await queryRunner.query(`ALTER TABLE \`city\` DROP FOREIGN KEY \`FK_e99de556ee56afe72154f3ed04a\``);
        await queryRunner.query(`ALTER TABLE \`state\` DROP FOREIGN KEY \`FK_e81c86ceadca8731f5fca8e06f5\``);
        await queryRunner.query(`ALTER TABLE \`user_detail\` DROP FOREIGN KEY \`FK_0bc43232b53a303a2a6eb40410f\``);
        await queryRunner.query(`ALTER TABLE \`user_detail\` DROP FOREIGN KEY \`FK_438c6137a1949713359a59e39de\``);
        await queryRunner.query(`ALTER TABLE \`user_detail\` DROP FOREIGN KEY \`FK_34b12bec10c7d1e5f5a6189f2a0\``);
        await queryRunner.query(`ALTER TABLE \`user_detail\` DROP FOREIGN KEY \`FK_0cb17ec996d935f159c77ee536f\``);
        await queryRunner.query(`ALTER TABLE \`user_detail\` DROP FOREIGN KEY \`FK_91b939d5697198c2b12ba36cddc\``);
        await queryRunner.query(`ALTER TABLE \`user_detail\` DROP FOREIGN KEY \`FK_f56bc266a9a1ef8912cbddb5754\``);
        await queryRunner.query(`ALTER TABLE \`user_detail\` DROP FOREIGN KEY \`FK_540d2de9f397b81fd7ee070d631\``);
        await queryRunner.query(`ALTER TABLE \`courses\` DROP FOREIGN KEY \`FK_a401fb96f1afa0fcebacd3e8e78\``);
        await queryRunner.query(`ALTER TABLE \`courses\` DROP FOREIGN KEY \`FK_fd1cecfbb001ebcd3a2221dff8c\``);
        await queryRunner.query(`ALTER TABLE \`courses\` DROP FOREIGN KEY \`FK_a09de3e6027500ac44609a8055f\``);
        await queryRunner.query(`ALTER TABLE \`courses\` DROP FOREIGN KEY \`FK_4fc71ca03df7fa563050d553c39\``);
        await queryRunner.query(`ALTER TABLE \`unit\` DROP FOREIGN KEY \`FK_c88f881f8a9aa8be02740289776\``);
        await queryRunner.query(`ALTER TABLE \`video_lecture\` DROP FOREIGN KEY \`FK_dfb3a19f9b575657e245f46d7a1\``);
        await queryRunner.query(`ALTER TABLE \`study_material\` DROP FOREIGN KEY \`FK_f7eb69acae2d90013542e3e584a\``);
        await queryRunner.query(`ALTER TABLE \`study_material\` DROP FOREIGN KEY \`FK_bb8358d7c0bc176266b00a3d345\``);
        await queryRunner.query(`ALTER TABLE \`user_progress\` DROP FOREIGN KEY \`FK_d6e1520d30ecc804051502cec69\``);
        await queryRunner.query(`ALTER TABLE \`user_progress\` DROP FOREIGN KEY \`FK_4e8ebae6a86a6d1483a0805f48c\``);
        await queryRunner.query(`ALTER TABLE \`user_progress\` DROP FOREIGN KEY \`FK_18a9800c645b27305a3d55961e8\``);
        await queryRunner.query(`ALTER TABLE \`user_progress\` DROP FOREIGN KEY \`FK_b5d0e1b57bc6c761fb49e79bf89\``);
        await queryRunner.query(`ALTER TABLE \`rating_feedback\` DROP FOREIGN KEY \`FK_3a4b6f59bafa155b2d185c6b1c6\``);
        await queryRunner.query(`ALTER TABLE \`notification\` DROP FOREIGN KEY \`FK_00abcf7b2089a5c05f0aedc5676\``);
        await queryRunner.query(`ALTER TABLE \`contact_us\` DROP FOREIGN KEY \`FK_21a409f03c342bf8bb747c90161\``);
        await queryRunner.query(`ALTER TABLE \`banner\` CHANGE \`imagePath\` \`imagePath\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`banner\` CHANGE \`image\` \`image\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`book_image\` CHANGE \`bookId\` \`bookId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`book\` CHANGE \`coverImagePath\` \`coverImagePath\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`book\` CHANGE \`coverImage\` \`coverImage\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`book\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`category\` CHANGE \`imagePath\` \`imagePath\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`category\` CHANGE \`image\` \`image\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`fixed_session\` CHANGE \`notes\` \`notes\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`fixed_session\` CHANGE \`purchaseId\` \`purchaseId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`faq\` CHANGE \`answer\` \`answer\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`faq\` CHANGE \`question\` \`question\` varchar(150) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`notice\` CHANGE \`imagePath\` \`imagePath\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`notice\` CHANGE \`image\` \`image\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`news\` CHANGE \`imagePath\` \`imagePath\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`news\` CHANGE \`image\` \`image\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`news\` CHANGE \`desc\` \`desc\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`news\` CHANGE \`heading\` \`heading\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`page\` CHANGE \`imagePath\` \`imagePath\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`page\` CHANGE \`imageUrl\` \`imageUrl\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`session\` CHANGE \`notes\` \`notes\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`session\` CHANGE \`purchaseId\` \`purchaseId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`session\` CHANGE \`amount\` \`amount\` decimal(10,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`search_history\` CHANGE \`accountId\` \`accountId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`search_history\` CHANGE \`keyword\` \`keyword\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`setting\` CHANGE \`whatsApp\` \`whatsApp\` varchar(500) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`setting\` CHANGE \`instagram\` \`instagram\` varchar(500) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`setting\` CHANGE \`twitter\` \`twitter\` varchar(500) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`setting\` CHANGE \`linkedIn\` \`linkedIn\` varchar(500) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`setting\` CHANGE \`facebook\` \`facebook\` varchar(500) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`setting\` CHANGE \`logoPath\` \`logoPath\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`setting\` CHANGE \`logo\` \`logo\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`setting\` CHANGE \`mobile_domain\` \`mobile_domain\` varchar(150) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`setting\` CHANGE \`admin_domain\` \`admin_domain\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`setting\` CHANGE \`user_domain\` \`user_domain\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`setting\` CHANGE \`title\` \`title\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tutor_block\` CHANGE \`reason\` \`reason\` varchar(200) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_purchase\` CHANGE \`expiresAt\` \`expiresAt\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_purchase\` CHANGE \`paymentIntentId\` \`paymentIntentId\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_purchase\` CHANGE \`transactionId\` \`transactionId\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_purchase\` CHANGE \`couponCode\` \`couponCode\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_purchase\` CHANGE \`originalAmount\` \`originalAmount\` decimal(10,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_purchase\` CHANGE \`merchantOrderId\` \`merchantOrderId\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_purchase\` CHANGE \`sessionId\` \`sessionId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_purchase\` CHANGE \`unitId\` \`unitId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_purchase\` CHANGE \`studyMaterialId\` \`studyMaterialId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_purchase\` CHANGE \`videoLectureId\` \`videoLectureId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_purchase\` CHANGE \`courseId\` \`courseId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`account\` CHANGE \`lockedUntil\` \`lockedUntil\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`account\` CHANGE \`password\` \`password\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`account\` CHANGE \`email\` \`email\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`account\` CHANGE \`phoneNumber\` \`phoneNumber\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_permission\` CHANGE \`permissionId\` \`permissionId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_permission\` CHANGE \`menuId\` \`menuId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_permission\` CHANGE \`accountId\` \`accountId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`staff_detail\` CHANGE \`updatedBy\` \`updatedBy\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`staff_detail\` CHANGE \`accountId\` \`accountId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`staff_detail\` CHANGE \`pin\` \`pin\` varchar(10) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`staff_detail\` CHANGE \`country\` \`country\` varchar(20) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`staff_detail\` CHANGE \`state\` \`state\` varchar(20) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`staff_detail\` CHANGE \`city\` \`city\` varchar(20) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`staff_detail\` CHANGE \`gender\` \`gender\` enum ('MALE', 'FEMALE', 'OTHERS') NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`staff_detail\` CHANGE \`dob\` \`dob\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`staff_detail\` CHANGE \`email\` \`email\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`staff_detail\` CHANGE \`name\` \`name\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rating\` CHANGE \`courseId\` \`courseId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rating\` CHANGE \`tutorId\` \`tutorId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rating\` CHANGE \`comment\` \`comment\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tutor_detail\` CHANGE \`qualificationId\` \`qualificationId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tutor_detail\` CHANGE \`languageId\` \`languageId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tutor_detail\` CHANGE \`countryId\` \`countryId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tutor_detail\` CHANGE \`subjectId\` \`subjectId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tutor_detail\` CHANGE \`cityId\` \`cityId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tutor_detail\` CHANGE \`accountId\` \`accountId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tutor_detail\` CHANGE \`bio\` \`bio\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tutor_detail\` CHANGE \`documentName\` \`documentName\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tutor_detail\` CHANGE \`document\` \`document\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tutor_detail\` CHANGE \`profileImagePath\` \`profileImagePath\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tutor_detail\` CHANGE \`profileImage\` \`profileImage\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tutor_detail\` CHANGE \`dob\` \`dob\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tutor_detail\` CHANGE \`gender\` \`gender\` enum ('MALE', 'FEMALE', 'OTHERS') NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tutor_detail\` CHANGE \`tutorId\` \`tutorId\` varchar(20) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tutor_detail\` CHANGE \`name\` \`name\` varchar(55) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`city\` CHANGE \`stateId\` \`stateId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`state\` CHANGE \`countryId\` \`countryId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`state\` CHANGE \`code\` \`code\` varchar(10) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`country\` CHANGE \`code\` \`code\` varchar(10) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_detail\` CHANGE \`qualificationId\` \`qualificationId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_detail\` CHANGE \`budgetId\` \`budgetId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_detail\` CHANGE \`languageId\` \`languageId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_detail\` CHANGE \`countryId\` \`countryId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_detail\` CHANGE \`goalId\` \`goalId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_detail\` CHANGE \`topicId\` \`topicId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_detail\` CHANGE \`accountId\` \`accountId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_detail\` CHANGE \`profileName\` \`profileName\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_detail\` CHANGE \`profile\` \`profile\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_detail\` CHANGE \`address\` \`address\` varchar(5000) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_detail\` CHANGE \`dob\` \`dob\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_detail\` CHANGE \`englishLevel\` \`englishLevel\` enum ('Beginner', 'Intermediate', 'Exparts', 'Pro_Master') NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_detail\` CHANGE \`gender\` \`gender\` enum ('MALE', 'FEMALE', 'OTHERS') NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_detail\` CHANGE \`name\` \`name\` varchar(55) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`topic\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`language\` CHANGE \`name\` \`name\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`courses\` CHANGE \`classId\` \`classId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`courses\` CHANGE \`deletionReason\` \`deletionReason\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`courses\` CHANGE \`languageId\` \`languageId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`courses\` CHANGE \`subjectId\` \`subjectId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`courses\` CHANGE \`endDate\` \`endDate\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`courses\` CHANGE \`startDate\` \`startDate\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`courses\` CHANGE \`authorMessage\` \`authorMessage\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`courses\` CHANGE \`totalDuration\` \`totalDuration\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`courses\` CHANGE \`thumbnailUrl\` \`thumbnailUrl\` varchar(500) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`courses\` CHANGE \`thumbnailpath\` \`thumbnailpath\` varchar(500) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`courses\` CHANGE \`imagepath\` \`imagepath\` varchar(500) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`courses\` CHANGE \`imageUrl\` \`imageUrl\` varchar(500) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`courses\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`unit\` CHANGE \`courseId\` \`courseId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`unit\` CHANGE \`imgPath\` \`imgPath\` varchar(200) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`unit\` CHANGE \`imgUrl\` \`imgUrl\` varchar(200) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`unit\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`video_lecture\` CHANGE \`thumbnailPath\` \`thumbnailPath\` varchar(500) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`video_lecture\` CHANGE \`thumbnailUrl\` \`thumbnailUrl\` varchar(500) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`video_lecture\` CHANGE \`videoPath\` \`videoPath\` varchar(500) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`video_lecture\` CHANGE \`videoUrl\` \`videoUrl\` varchar(500) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`video_lecture\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`study_material\` CHANGE \`unitId\` \`unitId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`study_material\` CHANGE \`filePath\` \`filePath\` varchar(500) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`study_material\` CHANGE \`fileUrl\` \`fileUrl\` varchar(500) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`study_material\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_progress\` CHANGE \`contentId\` \`contentId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_progress\` CHANGE \`studyMaterialId\` \`studyMaterialId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_progress\` CHANGE \`unitId\` \`unitId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_progress\` CHANGE \`courseId\` \`courseId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`class\` CHANGE \`imagePath\` \`imagePath\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`class\` CHANGE \`image\` \`image\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`subject\` CHANGE \`imagePath\` \`imagePath\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`subject\` CHANGE \`image\` \`image\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`subject\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rating_feedback\` CHANGE \`accountId\` \`accountId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`rating_feedback\` CHANGE \`desc\` \`desc\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`notification\` CHANGE \`accountId\` \`accountId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`notification\` CHANGE \`type\` \`type\` enum ('NEW PRODUCT', 'NEW ACCOUNT', 'CONTACT US', 'QNA', 'FEEDBACK', 'INVOICE', 'STAFF', 'TICKET', 'USER PRODUCT', 'USER ACCOUNT', 'USER INVOICE', 'USER PAYMENT', 'USER TICKET', 'OFFER', 'LOGIN', 'DEMO') NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`notification\` CHANGE \`desc\` \`desc\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`notification\` CHANGE \`title\` \`title\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`login_history\` CHANGE \`ip\` \`ip\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`login_history\` CHANGE \`logoutTime\` \`logoutTime\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`login_history\` CHANGE \`loginTime\` \`loginTime\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`contact_us\` CHANGE \`message\` \`message\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`contact_us\` CHANGE \`code\` \`code\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`contact_us\` CHANGE \`phoneNumber\` \`phoneNumber\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`contact_us\` CHANGE \`email\` \`email\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`contact_us\` CHANGE \`LastName\` \`LastName\` varchar(55) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`contact_us\` CHANGE \`firstName\` \`firstName\` varchar(55) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`contact_us\` CHANGE \`accountId\` \`accountId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`contact_us\` ADD CONSTRAINT \`FK_21a409f03c342bf8bb747c90161\` FOREIGN KEY (\`accountId\`) REFERENCES \`account\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`walk_through\` CHANGE \`imagePath\` \`imagePath\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`walk_through\` CHANGE \`image\` \`image\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`walk_through\` CHANGE \`subtitle\` \`subtitle\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`walk_through\` CHANGE \`title\` \`title\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`unit\` DROP COLUMN \`akashGhoshPath\``);
    }

}
